BEGIN;
DROP TABLE IF EXISTS "coffee", "category", "origin";

CREATE TABLE IF NOT EXISTS "category" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "origin" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "country" VARCHAR(100) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "coffee" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "reference" INTEGER NOT NULL UNIQUE,
  "price_per_kg" DECIMAL(10, 2) NOT NULL,
  "available" BOOLEAN NOT NULL,
  "category_id" INTEGER NOT NULL REFERENCES "category"("id"),
  "origin_id" INTEGER NOT NULL REFERENCES "origin"("id"),
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP
);

INSERT INTO "category" ("name")
VALUES
  ('Corsé'),
  ('Acide'),
  ('Fruité'),
  ('Doux'),
  ('Épicé'),
  ('Chocolaté');

INSERT INTO "origin" ("country")
VALUES
  ('Italie'),
  ('Colombie'),
  ('Éthiopie'),
  ('Brésil'),
  ('Guatemala'),
  ('Kenya'),
  ('Indonésie'),
  ('Costa Rica'),
  ('Vietnam'),
  ('Tanzanie'),
  ('Jamaïque'),
  ('Rwanda'),
  ('Panama'),
  ('Pérou'),
  ('Hawaï'),
  ('Nicaragua'),
  ('Équateur'),
  ('Ouganda'),
  ('République Dominicaine'),
  ('Papouasie-Nouvelle-Guinée');

INSERT INTO "coffee"
  ("name", "description", "reference", "price_per_kg", "available", "category_id", "origin_id")
VALUES
  ('Espresso', 'Café fort et concentré préparé en faisant passer de l''eau chaude à travers du café finement moulu.', 100955890, 20.99, TRUE, 1, 1),
  ('Columbian', 'Café moyennement corsé avec une acidité vive et une saveur riche.', 100955894, 18.75, TRUE, 2, 2),
  ('Ethiopian Yirgacheffe', 'Réputé pour son arôme floral, son acidité vive et ses notes de saveur citronnée.', 105589090, 22.50, TRUE, 3, 3),
  ('Brazilian Santos', 'Café doux et lisse avec un profil de saveur de noisette.', 134009550, 17.80, TRUE, 4, 4),
  ('Guatemalan Antigua', 'Café corsé avec des nuances chocolatées et une pointe d''épice.', 256505890, 21.25, TRUE, 1, 5),
  ('Kenyan AA', 'Café complexe connu pour son acidité rappelant le vin et ses saveurs fruitées.', 295432730, 23.70, TRUE, 2, 6),
  ('Sumatra Mandheling', 'Café profond et terreux avec un corps lourd et une faible acidité.', 302932754, 19.95, TRUE, 1, 7),
  ('Costa Rican Tarrazu', 'Café vif et net avec une finition propre et une acidité vive.', 327302954, 24.50, TRUE, 2, 8),
  ('Vietnamese Robusta', 'Café audacieux et fort avec une saveur robuste distinctive.', 549549090, 16.75, TRUE, 5, 9),
  ('Tanzanian Peaberry', 'Acidité vive avec un profil de saveur rappelant le vin et un corps moyen.', 582954954, 26.80, TRUE, 3, 10),
  ('Jamaican Blue Mountain', 'Reconnu pour sa saveur douce, son acidité vive et son absence d''amertume.', 589100954, 39.25, TRUE, 4, 11),
  ('Rwandan Bourbon', 'Café avec des notes florales prononcées, une acidité vive et un corps moyen.', 650753915, 21.90, TRUE, 3, 12),
  ('Panamanian Geisha', 'Café rare aux arômes floraux complexes, une acidité brillante et un profil de saveur distinctif.', 795501340, 42.00, TRUE, 3, 13),
  ('Peruvian Arabica', 'Café équilibré avec des notes de chocolat, une acidité modérée et un corps velouté.', 954589100, 19.40, FALSE, 6, 14),
  ('Hawaiian Kona', 'Café rare au goût riche, une acidité douce et des nuances subtiles.', 958090105, 55.75, FALSE, 4, 15),
  ('Nicaraguan Maragogipe', 'Café avec des notes de fruits, une acidité vive et un corps plein.', 691550753, 28.60, FALSE, 3, 16),
  ('Costa Rican Naranjo', 'Café de terroir qui révèle des saveurs d’amande, de noisette ainsi que des notes florales et boisées.', 465973216, 31.80, TRUE, 3, 8),
  ('Lojan Sierra', 'Café aux notes de raisins et de noisette. Une tasse équilibrée et raffinée.', 379843219, 41.20, FALSE, 4, 17),
  ('Kayanzan Inka', 'Café avec des notes de caramel et d''agrumes.', 798432023, 30.40, FALSE, 3, 17),
  ('Ugandan Zombo', 'Café des notes fruitées de pomme et de raisin.', 563942138, 44.90, TRUE, 3, 18),
  ('Ethiopian Sidamo', 'Café aux notes florales et fruitées, avec une acidité vive.', 981489743, 29.99, TRUE, 2, 3),
  ('Balinese Toya', 'Café séduisant avec ses notes de chocolat, de miel et des notes finales de fruits rouges.', 479321586, 40.30, TRUE, 4, 7),
  ('Dominican Iguana', 'Café aux notes gourmandes de noisettes et de chocolat au lait, avec des notes de caramel et fruitées avec du citron jaune.', 146973248, 31.80, FALSE, 4, 19),
  ('Papuan Raggiana', 'Café aux notes de noix, avec une belle acidité, des saveurs d''abricot et une pointe de rhubarbe.', 974235862, 33.00, TRUE, 2, 20);

COMMIT;